### ISSUE TITLE
Expo for web

### ISSUE THREAD

**Issue by dave-gohyperion** [JacopoPatroclo/nx-react-native-expo#1]
Very cool project, thanks for making it.

Is there a way to start `expo for web` through Nx? Which is normally started with: `expo start:web`

**Comment by JacopoPatroclo** [comment]
Sure, I will implement a new nx builder for the web.

But for right now, in theory you could run `nx start {yours app name}` and navigate to the expo web app (by default running on http://localhost:19002) and select "run on web" in the left bottom corner of the webpage. That should open another web page with your app in it. Let me know if it works.

**Comment by dave-gohyperion** [comment]
Oh very cool, never noticed that! That did indeed work, thank you.

**Comment by JacopoPatroclo** [comment]
@dave-gohyperion hi, now if you update to 0.0.5 you can use directly `run-web` to start the expo app in a web browser. There is a small fix to do to support this new version:
- Update the package to 0.0.5
- Inside workspace.json find the config for your expo app and add under run-android node
``` javascript
// ....
"run-web": {
     "builder": "nx-react-native-expo:run-web",
     "options": {}
},
// ....
```
- Copy the content of [this file](https://github.com/JacopoPatroclo/nx-react-native-expo/blob/master/packages/react-native-expo/src/schematics/application/files/app/webpack.config.js.template) into a file called `webpack.config.js` inside the base directory of your expo app.

- Try to use the new command

Let me know how it goes.

**Comment by dave-gohyperion** [comment]
Works great, thanks!
